//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.springframework.schema.beans.Bean;
import org.springframework.schema.beans.Ref;


/**
 * <p>Java class for chunkTaskletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chunkTaskletType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="reader" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="processor" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="writer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="skip-policy" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="retry-policy" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="retry-listeners" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="listener" type="{http://www.springframework.org/schema/batch}listenerType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="streams" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stream" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="skippable-exception-classes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}includeExcludeElementGroup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="retryable-exception-classes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}includeExcludeElementGroup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="listeners" type="{http://www.springframework.org/schema/batch}stepListenersType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="commit-interval" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reader" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="writer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skip-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skip-policy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retry-policy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retry-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cache-capacity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reader-transactional-queue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processor-transactional" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="chunk-completion-policy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chunkTaskletType", propOrder = {

})
public class ChunkTaskletType {

    @XmlElement(name = "reader")
    protected ChunkTaskletType.Reader readerAttribute;
    @XmlElement(name = "processor")
    protected ChunkTaskletType.Processor processorAttribute;
    @XmlElement(name = "writer")
    protected ChunkTaskletType.Writer writerAttribute;
    @XmlElement(name = "skip-policy")
    protected ChunkTaskletType.SkipPolicy skipPolicyAttribute;
    @XmlElement(name = "retry-policy")
    protected ChunkTaskletType.RetryPolicy retryPolicyAttribute;
    @XmlElement(name = "retry-listeners")
    protected ChunkTaskletType.RetryListeners retryListeners;
    protected ChunkTaskletType.Streams streams;
    @XmlElement(name = "skippable-exception-classes")
    protected ChunkTaskletType.SkippableExceptionClasses skippableExceptionClasses;
    @XmlElement(name = "retryable-exception-classes")
    protected ChunkTaskletType.RetryableExceptionClasses retryableExceptionClasses;
    protected StepListenersType listeners;
    @XmlAttribute(name = "commit-interval")
    protected String commitInterval;
    @XmlAttribute(name = "reader")
    protected String reader;
    @XmlAttribute(name = "processor")
    protected String processor;
    @XmlAttribute(name = "writer")
    protected String writer;
    @XmlAttribute(name = "skip-limit")
    protected String skipLimit;
    @XmlAttribute(name = "skip-policy")
    protected String skipPolicy;
    @XmlAttribute(name = "retry-policy")
    protected String retryPolicy;
    @XmlAttribute(name = "retry-limit")
    protected String retryLimit;
    @XmlAttribute(name = "cache-capacity")
    protected String cacheCapacity;
    @XmlAttribute(name = "reader-transactional-queue")
    protected String readerTransactionalQueue;
    @XmlAttribute(name = "processor-transactional")
    protected String processorTransactional;
    @XmlAttribute(name = "chunk-completion-policy")
    protected String chunkCompletionPolicy;

    /**
     * Gets the value of the readerAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.Reader }
     *     
     */
    public ChunkTaskletType.Reader getReaderAttribute() {
        return readerAttribute;
    }

    /**
     * Sets the value of the readerAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.Reader }
     *     
     */
    public void setReaderAttribute(ChunkTaskletType.Reader value) {
        this.readerAttribute = value;
    }

    /**
     * Gets the value of the processorAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.Processor }
     *     
     */
    public ChunkTaskletType.Processor getProcessorAttribute() {
        return processorAttribute;
    }

    /**
     * Sets the value of the processorAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.Processor }
     *     
     */
    public void setProcessorAttribute(ChunkTaskletType.Processor value) {
        this.processorAttribute = value;
    }

    /**
     * Gets the value of the writerAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.Writer }
     *     
     */
    public ChunkTaskletType.Writer getWriterAttribute() {
        return writerAttribute;
    }

    /**
     * Sets the value of the writerAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.Writer }
     *     
     */
    public void setWriterAttribute(ChunkTaskletType.Writer value) {
        this.writerAttribute = value;
    }

    /**
     * Gets the value of the skipPolicyAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.SkipPolicy }
     *     
     */
    public ChunkTaskletType.SkipPolicy getSkipPolicyAttribute() {
        return skipPolicyAttribute;
    }

    /**
     * Sets the value of the skipPolicyAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.SkipPolicy }
     *     
     */
    public void setSkipPolicyAttribute(ChunkTaskletType.SkipPolicy value) {
        this.skipPolicyAttribute = value;
    }

    /**
     * Gets the value of the retryPolicyAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.RetryPolicy }
     *     
     */
    public ChunkTaskletType.RetryPolicy getRetryPolicyAttribute() {
        return retryPolicyAttribute;
    }

    /**
     * Sets the value of the retryPolicyAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.RetryPolicy }
     *     
     */
    public void setRetryPolicyAttribute(ChunkTaskletType.RetryPolicy value) {
        this.retryPolicyAttribute = value;
    }

    /**
     * Gets the value of the retryListeners property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.RetryListeners }
     *     
     */
    public ChunkTaskletType.RetryListeners getRetryListeners() {
        return retryListeners;
    }

    /**
     * Sets the value of the retryListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.RetryListeners }
     *     
     */
    public void setRetryListeners(ChunkTaskletType.RetryListeners value) {
        this.retryListeners = value;
    }

    /**
     * Gets the value of the streams property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.Streams }
     *     
     */
    public ChunkTaskletType.Streams getStreams() {
        return streams;
    }

    /**
     * Sets the value of the streams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.Streams }
     *     
     */
    public void setStreams(ChunkTaskletType.Streams value) {
        this.streams = value;
    }

    /**
     * Gets the value of the skippableExceptionClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.SkippableExceptionClasses }
     *     
     */
    public ChunkTaskletType.SkippableExceptionClasses getSkippableExceptionClasses() {
        return skippableExceptionClasses;
    }

    /**
     * Sets the value of the skippableExceptionClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.SkippableExceptionClasses }
     *     
     */
    public void setSkippableExceptionClasses(ChunkTaskletType.SkippableExceptionClasses value) {
        this.skippableExceptionClasses = value;
    }

    /**
     * Gets the value of the retryableExceptionClasses property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType.RetryableExceptionClasses }
     *     
     */
    public ChunkTaskletType.RetryableExceptionClasses getRetryableExceptionClasses() {
        return retryableExceptionClasses;
    }

    /**
     * Sets the value of the retryableExceptionClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType.RetryableExceptionClasses }
     *     
     */
    public void setRetryableExceptionClasses(ChunkTaskletType.RetryableExceptionClasses value) {
        this.retryableExceptionClasses = value;
    }

    /**
     * Gets the value of the listeners property.
     * 
     * @return
     *     possible object is
     *     {@link StepListenersType }
     *     
     */
    public StepListenersType getListeners() {
        return listeners;
    }

    /**
     * Sets the value of the listeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepListenersType }
     *     
     */
    public void setListeners(StepListenersType value) {
        this.listeners = value;
    }

    /**
     * Gets the value of the commitInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitInterval() {
        return commitInterval;
    }

    /**
     * Sets the value of the commitInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitInterval(String value) {
        this.commitInterval = value;
    }

    /**
     * Gets the value of the reader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReader() {
        return reader;
    }

    /**
     * Sets the value of the reader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReader(String value) {
        this.reader = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessor(String value) {
        this.processor = value;
    }

    /**
     * Gets the value of the writer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWriter() {
        return writer;
    }

    /**
     * Sets the value of the writer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWriter(String value) {
        this.writer = value;
    }

    /**
     * Gets the value of the skipLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkipLimit() {
        return skipLimit;
    }

    /**
     * Sets the value of the skipLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkipLimit(String value) {
        this.skipLimit = value;
    }

    /**
     * Gets the value of the skipPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkipPolicy() {
        return skipPolicy;
    }

    /**
     * Sets the value of the skipPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkipPolicy(String value) {
        this.skipPolicy = value;
    }

    /**
     * Gets the value of the retryPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetryPolicy() {
        return retryPolicy;
    }

    /**
     * Sets the value of the retryPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetryPolicy(String value) {
        this.retryPolicy = value;
    }

    /**
     * Gets the value of the retryLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetryLimit() {
        return retryLimit;
    }

    /**
     * Sets the value of the retryLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetryLimit(String value) {
        this.retryLimit = value;
    }

    /**
     * Gets the value of the cacheCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCacheCapacity() {
        return cacheCapacity;
    }

    /**
     * Sets the value of the cacheCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCacheCapacity(String value) {
        this.cacheCapacity = value;
    }

    /**
     * Gets the value of the readerTransactionalQueue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaderTransactionalQueue() {
        return readerTransactionalQueue;
    }

    /**
     * Sets the value of the readerTransactionalQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaderTransactionalQueue(String value) {
        this.readerTransactionalQueue = value;
    }

    /**
     * Gets the value of the processorTransactional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessorTransactional() {
        return processorTransactional;
    }

    /**
     * Sets the value of the processorTransactional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessorTransactional(String value) {
        this.processorTransactional = value;
    }

    /**
     * Gets the value of the chunkCompletionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChunkCompletionPolicy() {
        return chunkCompletionPolicy;
    }

    /**
     * Sets the value of the chunkCompletionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChunkCompletionPolicy(String value) {
        this.chunkCompletionPolicy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bean",
        "refAttribute"
    })
    public static class Processor {

        @XmlElement(namespace = "http://www.springframework.org/schema/beans")
        protected Bean bean;
        @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
        protected Ref refAttribute;
        @XmlAttribute(name = "adapter-method")
        protected String adapterMethod;

        /**
         * Gets the value of the bean property.
         * 
         * @return
         *     possible object is
         *     {@link Bean }
         *     
         */
        public Bean getBean() {
            return bean;
        }

        /**
         * Sets the value of the bean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bean }
         *     
         */
        public void setBean(Bean value) {
            this.bean = value;
        }

        /**
         * Gets the value of the refAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Ref }
         *     
         */
        public Ref getRefAttribute() {
            return refAttribute;
        }

        /**
         * Sets the value of the refAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ref }
         *     
         */
        public void setRefAttribute(Ref value) {
            this.refAttribute = value;
        }

        /**
         * Gets the value of the adapterMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterMethod() {
            return adapterMethod;
        }

        /**
         * Sets the value of the adapterMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterMethod(String value) {
            this.adapterMethod = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bean",
        "refAttribute"
    })
    public static class Reader {

        @XmlElement(namespace = "http://www.springframework.org/schema/beans")
        protected Bean bean;
        @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
        protected Ref refAttribute;
        @XmlAttribute(name = "adapter-method")
        protected String adapterMethod;

        /**
         * Gets the value of the bean property.
         * 
         * @return
         *     possible object is
         *     {@link Bean }
         *     
         */
        public Bean getBean() {
            return bean;
        }

        /**
         * Sets the value of the bean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bean }
         *     
         */
        public void setBean(Bean value) {
            this.bean = value;
        }

        /**
         * Gets the value of the refAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Ref }
         *     
         */
        public Ref getRefAttribute() {
            return refAttribute;
        }

        /**
         * Sets the value of the refAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ref }
         *     
         */
        public void setRefAttribute(Ref value) {
            this.refAttribute = value;
        }

        /**
         * Gets the value of the adapterMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterMethod() {
            return adapterMethod;
        }

        /**
         * Sets the value of the adapterMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterMethod(String value) {
            this.adapterMethod = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}includeExcludeElementGroup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "includeExcludeElementGroup"
    })
    public static class RetryableExceptionClasses {

        @XmlElements({
            @XmlElement(name = "include", type = ChunkTaskletType.RetryableExceptionClasses.Include.class),
            @XmlElement(name = "exclude", type = ChunkTaskletType.RetryableExceptionClasses.Exclude.class)
        })
        protected List<Object> includeExcludeElementGroup;
        @XmlAttribute(name = "merge")
        protected Boolean merge;

        /**
         * Gets the value of the includeExcludeElementGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the includeExcludeElementGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncludeExcludeElementGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChunkTaskletType.RetryableExceptionClasses.Include }
         * {@link ChunkTaskletType.RetryableExceptionClasses.Exclude }
         * 
         * 
         */
        public List<Object> getIncludeExcludeElementGroup() {
            if (includeExcludeElementGroup == null) {
                includeExcludeElementGroup = new ArrayList<Object>();
            }
            return this.includeExcludeElementGroup;
        }

        /**
         * Gets the value of the merge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMerge() {
            return merge;
        }

        /**
         * Sets the value of the merge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMerge(Boolean value) {
            this.merge = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}exceptionClassAttribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Exclude {

            @XmlAttribute(name = "class", required = true)
            protected String clazz;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}exceptionClassAttribute"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Include {

            @XmlAttribute(name = "class", required = true)
            protected String clazz;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="listener" type="{http://www.springframework.org/schema/batch}listenerType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listener"
    })
    public static class RetryListeners {

        protected List<ListenerType> listener;
        @XmlAttribute(name = "merge")
        protected Boolean merge;

        /**
         * Gets the value of the listener property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the listener property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getListener().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ListenerType }
         * 
         * 
         */
        public List<ListenerType> getListener() {
            if (listener == null) {
                listener = new ArrayList<ListenerType>();
            }
            return this.listener;
        }

        /**
         * Gets the value of the merge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMerge() {
            return merge;
        }

        /**
         * Sets the value of the merge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMerge(Boolean value) {
            this.merge = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bean",
        "refAttribute"
    })
    public static class RetryPolicy {

        @XmlElement(namespace = "http://www.springframework.org/schema/beans")
        protected Bean bean;
        @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
        protected Ref refAttribute;
        @XmlAttribute(name = "adapter-method")
        protected String adapterMethod;

        /**
         * Gets the value of the bean property.
         * 
         * @return
         *     possible object is
         *     {@link Bean }
         *     
         */
        public Bean getBean() {
            return bean;
        }

        /**
         * Sets the value of the bean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bean }
         *     
         */
        public void setBean(Bean value) {
            this.bean = value;
        }

        /**
         * Gets the value of the refAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Ref }
         *     
         */
        public Ref getRefAttribute() {
            return refAttribute;
        }

        /**
         * Sets the value of the refAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ref }
         *     
         */
        public void setRefAttribute(Ref value) {
            this.refAttribute = value;
        }

        /**
         * Gets the value of the adapterMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterMethod() {
            return adapterMethod;
        }

        /**
         * Sets the value of the adapterMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterMethod(String value) {
            this.adapterMethod = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}includeExcludeElementGroup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "includeExcludeElementGroup"
    })
    public static class SkippableExceptionClasses {

        @XmlElements({
            @XmlElement(name = "include", type = ChunkTaskletType.RetryableExceptionClasses.Include.class),
            @XmlElement(name = "exclude", type = ChunkTaskletType.RetryableExceptionClasses.Exclude.class)
        })
        protected List<Object> includeExcludeElementGroup;
        @XmlAttribute(name = "merge")
        protected Boolean merge;

        /**
         * Gets the value of the includeExcludeElementGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the includeExcludeElementGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncludeExcludeElementGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChunkTaskletType.RetryableExceptionClasses.Include }
         * {@link ChunkTaskletType.RetryableExceptionClasses.Exclude }
         * 
         * 
         */
        public List<Object> getIncludeExcludeElementGroup() {
            if (includeExcludeElementGroup == null) {
                includeExcludeElementGroup = new ArrayList<Object>();
            }
            return this.includeExcludeElementGroup;
        }

        /**
         * Gets the value of the merge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMerge() {
            return merge;
        }

        /**
         * Sets the value of the merge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMerge(Boolean value) {
            this.merge = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bean",
        "refAttribute"
    })
    public static class SkipPolicy {

        @XmlElement(namespace = "http://www.springframework.org/schema/beans")
        protected Bean bean;
        @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
        protected Ref refAttribute;
        @XmlAttribute(name = "adapter-method")
        protected String adapterMethod;

        /**
         * Gets the value of the bean property.
         * 
         * @return
         *     possible object is
         *     {@link Bean }
         *     
         */
        public Bean getBean() {
            return bean;
        }

        /**
         * Sets the value of the bean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bean }
         *     
         */
        public void setBean(Bean value) {
            this.bean = value;
        }

        /**
         * Gets the value of the refAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Ref }
         *     
         */
        public Ref getRefAttribute() {
            return refAttribute;
        }

        /**
         * Sets the value of the refAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ref }
         *     
         */
        public void setRefAttribute(Ref value) {
            this.refAttribute = value;
        }

        /**
         * Gets the value of the adapterMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterMethod() {
            return adapterMethod;
        }

        /**
         * Sets the value of the adapterMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterMethod(String value) {
            this.adapterMethod = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Streams {

        protected List<ChunkTaskletType.Streams.Stream> stream;
        @XmlAttribute(name = "merge")
        protected Boolean merge;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChunkTaskletType.Streams.Stream }
         * 
         * 
         */
        public List<ChunkTaskletType.Streams.Stream> getStream() {
            if (stream == null) {
                stream = new ArrayList<ChunkTaskletType.Streams.Stream>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the merge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMerge() {
            return merge;
        }

        /**
         * Sets the value of the merge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMerge(Boolean value) {
            this.merge = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stream {

            @XmlAttribute(name = "ref")
            protected String ref;

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRef(String value) {
                this.ref = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}adapterMethodAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bean",
        "refAttribute"
    })
    public static class Writer {

        @XmlElement(namespace = "http://www.springframework.org/schema/beans")
        protected Bean bean;
        @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
        protected Ref refAttribute;
        @XmlAttribute(name = "adapter-method")
        protected String adapterMethod;

        /**
         * Gets the value of the bean property.
         * 
         * @return
         *     possible object is
         *     {@link Bean }
         *     
         */
        public Bean getBean() {
            return bean;
        }

        /**
         * Sets the value of the bean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bean }
         *     
         */
        public void setBean(Bean value) {
            this.bean = value;
        }

        /**
         * Gets the value of the refAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Ref }
         *     
         */
        public Ref getRefAttribute() {
            return refAttribute;
        }

        /**
         * Sets the value of the refAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ref }
         *     
         */
        public void setRefAttribute(Ref value) {
            this.refAttribute = value;
        }

        /**
         * Gets the value of the adapterMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterMethod() {
            return adapterMethod;
        }

        /**
         * Sets the value of the adapterMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterMethod(String value) {
            this.adapterMethod = value;
        }

    }

}
