//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.springframework.schema.beans.Bean;
import org.springframework.schema.beans.Ref;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.springframework.org/schema/batch}description" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;group ref="{http://www.springframework.org/schema/batch}flowGroup" maxOccurs="unbounded"/>
 *           &lt;element name="listeners">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="listener" type="{http://www.springframework.org/schema/batch}jobExecutionListenerType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="validator">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
 *                   &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}jobRepositoryAttribute"/>
 *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}parentAttribute"/>
 *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}abstractAttribute"/>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="incrementer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="restartable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "stepOrSplitOrFlow"
})
@XmlRootElement(name = "job")
public class Job {

    protected String description;
    @XmlElements({
        @XmlElement(name = "step", type = Job.Step.class),
        @XmlElement(name = "split", type = Job.Split.class),
        @XmlElement(name = "flow", type = Job.Flow.class),
        @XmlElement(name = "decision", type = Job.Decision.class),
        @XmlElement(name = "listeners", type = Job.Listeners.class),
        @XmlElement(name = "validator", type = Job.Validator.class)
    })
    protected List<Object> stepOrSplitOrFlow;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "incrementer")
    protected String incrementer;
    @XmlAttribute(name = "restartable")
    protected String restartable;
    @XmlAttribute(name = "job-repository")
    protected String jobRepository;
    @XmlAttribute(name = "parent")
    protected String parent;
    @XmlAttribute(name = "abstract")
    protected Boolean _abstract;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the stepOrSplitOrFlow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stepOrSplitOrFlow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStepOrSplitOrFlow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Job.Step }
     * {@link Job.Split }
     * {@link Job.Flow }
     * {@link Job.Decision }
     * {@link Job.Listeners }
     * {@link Job.Validator }
     * 
     * 
     */
    public List<Object> getStepOrSplitOrFlow() {
        if (stepOrSplitOrFlow == null) {
            stepOrSplitOrFlow = new ArrayList<Object>();
        }
        return this.stepOrSplitOrFlow;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the incrementer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncrementer() {
        return incrementer;
    }

    /**
     * Sets the value of the incrementer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncrementer(String value) {
        this.incrementer = value;
    }

    /**
     * Gets the value of the restartable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestartable() {
        return restartable;
    }

    /**
     * Sets the value of the restartable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestartable(String value) {
        this.restartable = value;
    }

    /**
     * Gets the value of the jobRepository property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobRepository() {
        return jobRepository;
    }

    /**
     * Sets the value of the jobRepository property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobRepository(String value) {
        this.jobRepository = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstract(Boolean value) {
        this._abstract = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}transitions" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *       &lt;attribute name="decider" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transitions"
    })
    public static class Decision {

        @XmlElements({
            @XmlElement(name = "next", type = StepType.Next.class),
            @XmlElement(name = "stop", type = StepType.Stop.class),
            @XmlElement(name = "end", type = StepType.End.class),
            @XmlElement(name = "fail", type = StepType.Fail.class)
        })
        protected List<Object> transitions;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "decider", required = true)
        protected String decider;

        /**
         * Gets the value of the transitions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transitions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransitions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StepType.Next }
         * {@link StepType.Stop }
         * {@link StepType.End }
         * {@link StepType.Fail }
         * 
         * 
         */
        public List<Object> getTransitions() {
            if (transitions == null) {
                transitions = new ArrayList<Object>();
            }
            return this.transitions;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the decider property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecider() {
            return decider;
        }

        /**
         * Sets the value of the decider property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecider(String value) {
            this.decider = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}transitions" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}nextAttribute"/>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *       &lt;attribute name="parent" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transitions"
    })
    public static class Flow {

        @XmlElements({
            @XmlElement(name = "next", type = StepType.Next.class),
            @XmlElement(name = "stop", type = StepType.Stop.class),
            @XmlElement(name = "end", type = StepType.End.class),
            @XmlElement(name = "fail", type = StepType.Fail.class)
        })
        protected List<Object> transitions;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "parent", required = true)
        protected String parent;
        @XmlAttribute(name = "next")
        protected String next;

        /**
         * Gets the value of the transitions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transitions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransitions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StepType.Next }
         * {@link StepType.Stop }
         * {@link StepType.End }
         * {@link StepType.Fail }
         * 
         * 
         */
        public List<Object> getTransitions() {
            if (transitions == null) {
                transitions = new ArrayList<Object>();
            }
            return this.transitions;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the parent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParent() {
            return parent;
        }

        /**
         * Sets the value of the parent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParent(String value) {
            this.parent = value;
        }

        /**
         * Gets the value of the next property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNext() {
            return next;
        }

        /**
         * Sets the value of the next property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNext(String value) {
            this.next = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="listener" type="{http://www.springframework.org/schema/batch}jobExecutionListenerType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listener"
    })
    public static class Listeners {

        protected List<JobExecutionListenerType> listener;
        @XmlAttribute(name = "merge")
        protected Boolean merge;

        /**
         * Gets the value of the listener property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the listener property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getListener().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JobExecutionListenerType }
         * 
         * 
         */
        public List<JobExecutionListenerType> getListener() {
            if (listener == null) {
                listener = new ArrayList<JobExecutionListenerType>();
            }
            return this.listener;
        }

        /**
         * Gets the value of the merge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMerge() {
            return merge;
        }

        /**
         * Sets the value of the merge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMerge(Boolean value) {
            this.merge = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="flow">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;group ref="{http://www.springframework.org/schema/batch}flowGroup" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;group ref="{http://www.springframework.org/schema/batch}transitions"/>
     *       &lt;/choice>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}nextAttribute"/>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *       &lt;attribute name="task-executor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flowOrNextOrStop"
    })
    public static class Split {

        @XmlElements({
            @XmlElement(name = "flow", type = Job.Split.Flow.class),
            @XmlElement(name = "next", type = StepType.Next.class),
            @XmlElement(name = "stop", type = StepType.Stop.class),
            @XmlElement(name = "end", type = StepType.End.class),
            @XmlElement(name = "fail", type = StepType.Fail.class)
        })
        protected List<Object> flowOrNextOrStop;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "task-executor")
        protected String taskExecutor;
        @XmlAttribute(name = "next")
        protected String next;

        /**
         * Gets the value of the flowOrNextOrStop property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flowOrNextOrStop property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlowOrNextOrStop().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Job.Split.Flow }
         * {@link StepType.Next }
         * {@link StepType.Stop }
         * {@link StepType.End }
         * {@link StepType.Fail }
         * 
         * 
         */
        public List<Object> getFlowOrNextOrStop() {
            if (flowOrNextOrStop == null) {
                flowOrNextOrStop = new ArrayList<Object>();
            }
            return this.flowOrNextOrStop;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the taskExecutor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaskExecutor() {
            return taskExecutor;
        }

        /**
         * Sets the value of the taskExecutor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaskExecutor(String value) {
            this.taskExecutor = value;
        }

        /**
         * Gets the value of the next property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNext() {
            return next;
        }

        /**
         * Sets the value of the next property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNext(String value) {
            this.next = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;group ref="{http://www.springframework.org/schema/batch}flowGroup" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "flowGroup"
        })
        public static class Flow {

            @XmlElements({
                @XmlElement(name = "step", type = Job.Step.class),
                @XmlElement(name = "split", type = Job.Split.class),
                @XmlElement(name = "flow", type = Job.Flow.class),
                @XmlElement(name = "decision", type = Job.Decision.class)
            })
            protected List<Object> flowGroup;
            @XmlAttribute(name = "parent")
            protected String parent;

            /**
             * Gets the value of the flowGroup property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the flowGroup property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFlowGroup().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Job.Step }
             * {@link Job.Split }
             * {@link Job.Flow }
             * {@link Job.Decision }
             * 
             * 
             */
            public List<Object> getFlowGroup() {
                if (flowGroup == null) {
                    flowGroup = new ArrayList<Object>();
                }
                return this.flowGroup;
            }

            /**
             * Gets the value of the parent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParent() {
                return parent;
            }

            /**
             * Sets the value of the parent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParent(String value) {
                this.parent = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.springframework.org/schema/batch}stepType">
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}allowStartIfCompleteAttribute"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}nextAttribute"/>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Step
        extends StepType
    {

        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "allow-start-if-complete")
        protected String allowStartIfComplete;
        @XmlAttribute(name = "next")
        protected String next;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the allowStartIfComplete property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowStartIfComplete() {
            return allowStartIfComplete;
        }

        /**
         * Sets the value of the allowStartIfComplete property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowStartIfComplete(String value) {
            this.allowStartIfComplete = value;
        }

        /**
         * Gets the value of the next property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNext() {
            return next;
        }

        /**
         * Sets the value of the next property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNext(String value) {
            this.next = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}beanElementGroup" minOccurs="0"/>
     *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bean",
        "refAttribute"
    })
    public static class Validator {

        @XmlElement(namespace = "http://www.springframework.org/schema/beans")
        protected Bean bean;
        @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
        protected Ref refAttribute;
        @XmlAttribute(name = "ref")
        @XmlSchemaType(name = "anySimpleType")
        protected String ref;

        /**
         * Gets the value of the bean property.
         * 
         * @return
         *     possible object is
         *     {@link Bean }
         *     
         */
        public Bean getBean() {
            return bean;
        }

        /**
         * Sets the value of the bean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bean }
         *     
         */
        public void setBean(Bean value) {
            this.bean = value;
        }

        /**
         * Gets the value of the refAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link Ref }
         *     
         */
        public Ref getRefAttribute() {
            return refAttribute;
        }

        /**
         * Sets the value of the refAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ref }
         *     
         */
        public void setRefAttribute(Ref value) {
            this.refAttribute = value;
        }

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRef(String value) {
            this.ref = value;
        }

    }

}
