//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jobExecutionListenerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jobExecutionListenerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.springframework.org/schema/batch}listenerType">
 *       &lt;attribute name="before-job-method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="after-job-method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jobExecutionListenerType")
@XmlSeeAlso({
    JobListener.class
})
public class JobExecutionListenerType
    extends ListenerType
{

    @XmlAttribute(name = "before-job-method")
    protected String beforeJobMethod;
    @XmlAttribute(name = "after-job-method")
    protected String afterJobMethod;

    /**
     * Gets the value of the beforeJobMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeJobMethod() {
        return beforeJobMethod;
    }

    /**
     * Sets the value of the beforeJobMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeJobMethod(String value) {
        this.beforeJobMethod = value;
    }

    /**
     * Gets the value of the afterJobMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterJobMethod() {
        return afterJobMethod;
    }

    /**
     * Sets the value of the afterJobMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterJobMethod(String value) {
        this.afterJobMethod = value;
    }

}
