//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.springframework.schema.beans.IdentifiedType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.springframework.org/schema/beans}identifiedType">
 *       &lt;attribute name="data-source" type="{http://www.w3.org/2001/XMLSchema}string" default="dataSource" />
 *       &lt;attribute name="jdbc-operations" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transaction-manager" type="{http://www.w3.org/2001/XMLSchema}string" default="transactionManager" />
 *       &lt;attribute name="isolation-level-for-create" type="{http://www.springframework.org/schema/batch}isolationType" default="SERIALIZABLE" />
 *       &lt;attribute name="max-varchar-length" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="table-prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serializer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lob-handler" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "job-repository")
public class JobRepository
    extends IdentifiedType
{

    @XmlAttribute(name = "data-source")
    protected String dataSource;
    @XmlAttribute(name = "jdbc-operations")
    protected String jdbcOperations;
    @XmlAttribute(name = "transaction-manager")
    protected String transactionManager;
    @XmlAttribute(name = "isolation-level-for-create")
    protected IsolationType isolationLevelForCreate;
    @XmlAttribute(name = "max-varchar-length")
    protected Integer maxVarcharLength;
    @XmlAttribute(name = "table-prefix")
    protected String tablePrefix;
    @XmlAttribute(name = "serializer")
    protected String serializer;
    @XmlAttribute(name = "lob-handler")
    protected String lobHandler;

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSource() {
        if (dataSource == null) {
            return "dataSource";
        } else {
            return dataSource;
        }
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSource(String value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the jdbcOperations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcOperations() {
        return jdbcOperations;
    }

    /**
     * Sets the value of the jdbcOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcOperations(String value) {
        this.jdbcOperations = value;
    }

    /**
     * Gets the value of the transactionManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionManager() {
        if (transactionManager == null) {
            return "transactionManager";
        } else {
            return transactionManager;
        }
    }

    /**
     * Sets the value of the transactionManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionManager(String value) {
        this.transactionManager = value;
    }

    /**
     * Gets the value of the isolationLevelForCreate property.
     * 
     * @return
     *     possible object is
     *     {@link IsolationType }
     *     
     */
    public IsolationType getIsolationLevelForCreate() {
        if (isolationLevelForCreate == null) {
            return IsolationType.SERIALIZABLE;
        } else {
            return isolationLevelForCreate;
        }
    }

    /**
     * Sets the value of the isolationLevelForCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsolationType }
     *     
     */
    public void setIsolationLevelForCreate(IsolationType value) {
        this.isolationLevelForCreate = value;
    }

    /**
     * Gets the value of the maxVarcharLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxVarcharLength() {
        return maxVarcharLength;
    }

    /**
     * Sets the value of the maxVarcharLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxVarcharLength(Integer value) {
        this.maxVarcharLength = value;
    }

    /**
     * Gets the value of the tablePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTablePrefix() {
        return tablePrefix;
    }

    /**
     * Sets the value of the tablePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTablePrefix(String value) {
        this.tablePrefix = value;
    }

    /**
     * Gets the value of the serializer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerializer() {
        return serializer;
    }

    /**
     * Sets the value of the serializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerializer(String value) {
        this.serializer = value;
    }

    /**
     * Gets the value of the lobHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLobHandler() {
        return lobHandler;
    }

    /**
     * Sets the value of the lobHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLobHandler(String value) {
        this.lobHandler = value;
    }

}
