//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for partitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="partitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="step" type="{http://www.springframework.org/schema/batch}stepType" minOccurs="0"/>
 *         &lt;element name="handler" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="task-executor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="grid-size" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="handler" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="aggregator" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="partitioner" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "partitionType", propOrder = {

})
public class PartitionType {

    @XmlElement(name = "step")
    protected StepType stepAttribute;
    @XmlElement(name = "handler")
    protected PartitionType.Handler handlerAttribute;
    @XmlAttribute(name = "handler")
    @XmlSchemaType(name = "anySimpleType")
    protected String handler;
    @XmlAttribute(name = "aggregator")
    @XmlSchemaType(name = "anySimpleType")
    protected String aggregator;
    @XmlAttribute(name = "partitioner")
    @XmlSchemaType(name = "anySimpleType")
    protected String partitioner;
    @XmlAttribute(name = "step")
    @XmlSchemaType(name = "anySimpleType")
    protected String step;

    /**
     * Gets the value of the stepAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link StepType }
     *     
     */
    public StepType getStepAttribute() {
        return stepAttribute;
    }

    /**
     * Sets the value of the stepAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepType }
     *     
     */
    public void setStepAttribute(StepType value) {
        this.stepAttribute = value;
    }

    /**
     * Gets the value of the handlerAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link PartitionType.Handler }
     *     
     */
    public PartitionType.Handler getHandlerAttribute() {
        return handlerAttribute;
    }

    /**
     * Sets the value of the handlerAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartitionType.Handler }
     *     
     */
    public void setHandlerAttribute(PartitionType.Handler value) {
        this.handlerAttribute = value;
    }

    /**
     * Gets the value of the handler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandler() {
        return handler;
    }

    /**
     * Sets the value of the handler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandler(String value) {
        this.handler = value;
    }

    /**
     * Gets the value of the aggregator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregator() {
        return aggregator;
    }

    /**
     * Sets the value of the aggregator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregator(String value) {
        this.aggregator = value;
    }

    /**
     * Gets the value of the partitioner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitioner() {
        return partitioner;
    }

    /**
     * Sets the value of the partitioner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitioner(String value) {
        this.partitioner = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStep(String value) {
        this.step = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="task-executor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="grid-size" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Handler {

        @XmlAttribute(name = "task-executor")
        @XmlSchemaType(name = "anySimpleType")
        protected String taskExecutor;
        @XmlAttribute(name = "grid-size")
        @XmlSchemaType(name = "anySimpleType")
        protected String gridSize;

        /**
         * Gets the value of the taskExecutor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaskExecutor() {
            return taskExecutor;
        }

        /**
         * Sets the value of the taskExecutor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaskExecutor(String value) {
            this.taskExecutor = value;
        }

        /**
         * Gets the value of the gridSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGridSize() {
            return gridSize;
        }

        /**
         * Sets the value of the gridSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGridSize(String value) {
            this.gridSize = value;
        }

    }

}
