//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for stepType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stepType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.springframework.org/schema/batch}description" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;choice>
 *             &lt;element name="tasklet" type="{http://www.springframework.org/schema/batch}taskletType"/>
 *             &lt;any processContents='skip' namespace='##other'/>
 *           &lt;/choice>
 *           &lt;element name="partition" type="{http://www.springframework.org/schema/batch}partitionType"/>
 *           &lt;element name="job">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                   &lt;attribute name="job-launcher" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                   &lt;attribute name="job-parameters-extractor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="flow">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="parent" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;group ref="{http://www.springframework.org/schema/batch}transitions" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="listeners" type="{http://www.springframework.org/schema/batch}stepListenersType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}parentAttribute"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stepType", propOrder = {
    "description",
    "tasklet",
    "any",
    "partition",
    "job",
    "flow",
    "transitions",
    "listeners"
})
@XmlSeeAlso({
    org.springframework.schema.batch.Job.Step.class,
    org.springframework.schema.batch.Step.class
})
public class StepType {

    protected String description;
    protected TaskletType tasklet;
    @XmlAnyElement
    protected Element any;
    protected PartitionType partition;
    protected StepType.Job job;
    protected StepType.Flow flow;
    @XmlElements({
        @XmlElement(name = "next", type = StepType.Next.class),
        @XmlElement(name = "stop", type = StepType.Stop.class),
        @XmlElement(name = "end", type = StepType.End.class),
        @XmlElement(name = "fail", type = StepType.Fail.class)
    })
    protected List<Object> transitions;
    protected StepListenersType listeners;
    @XmlAttribute(name = "parent")
    protected String parent;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the tasklet property.
     * 
     * @return
     *     possible object is
     *     {@link TaskletType }
     *     
     */
    public TaskletType getTasklet() {
        return tasklet;
    }

    /**
     * Sets the value of the tasklet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskletType }
     *     
     */
    public void setTasklet(TaskletType value) {
        this.tasklet = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Element }
     *     
     */
    public Element getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Element }
     *     
     */
    public void setAny(Element value) {
        this.any = value;
    }

    /**
     * Gets the value of the partition property.
     * 
     * @return
     *     possible object is
     *     {@link PartitionType }
     *     
     */
    public PartitionType getPartition() {
        return partition;
    }

    /**
     * Sets the value of the partition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartitionType }
     *     
     */
    public void setPartition(PartitionType value) {
        this.partition = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link StepType.Job }
     *     
     */
    public StepType.Job getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepType.Job }
     *     
     */
    public void setJob(StepType.Job value) {
        this.job = value;
    }

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link StepType.Flow }
     *     
     */
    public StepType.Flow getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepType.Flow }
     *     
     */
    public void setFlow(StepType.Flow value) {
        this.flow = value;
    }

    /**
     * Gets the value of the transitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StepType.Next }
     * {@link StepType.Stop }
     * {@link StepType.End }
     * {@link StepType.Fail }
     * 
     * 
     */
    public List<Object> getTransitions() {
        if (transitions == null) {
            transitions = new ArrayList<Object>();
        }
        return this.transitions;
    }

    /**
     * Gets the value of the listeners property.
     * 
     * @return
     *     possible object is
     *     {@link StepListenersType }
     *     
     */
    public StepListenersType getListeners() {
        return listeners;
    }

    /**
     * Sets the value of the listeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepListenersType }
     *     
     */
    public void setListeners(StepListenersType value) {
        this.listeners = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="on" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="exit-code" type="{http://www.w3.org/2001/XMLSchema}string" default="COMPLETED" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class End {

        @XmlAttribute(name = "on", required = true)
        protected String on;
        @XmlAttribute(name = "exit-code")
        protected String exitCode;

        /**
         * Gets the value of the on property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOn() {
            return on;
        }

        /**
         * Sets the value of the on property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOn(String value) {
            this.on = value;
        }

        /**
         * Gets the value of the exitCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExitCode() {
            if (exitCode == null) {
                return "COMPLETED";
            } else {
                return exitCode;
            }
        }

        /**
         * Sets the value of the exitCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExitCode(String value) {
            this.exitCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="on" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="exit-code" type="{http://www.w3.org/2001/XMLSchema}string" default="FAILED" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Fail {

        @XmlAttribute(name = "on", required = true)
        protected String on;
        @XmlAttribute(name = "exit-code")
        protected String exitCode;

        /**
         * Gets the value of the on property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOn() {
            return on;
        }

        /**
         * Sets the value of the on property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOn(String value) {
            this.on = value;
        }

        /**
         * Gets the value of the exitCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExitCode() {
            if (exitCode == null) {
                return "FAILED";
            } else {
                return exitCode;
            }
        }

        /**
         * Sets the value of the exitCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExitCode(String value) {
            this.exitCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="parent" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Flow {

        @XmlAttribute(name = "parent", required = true)
        protected String parent;

        /**
         * Gets the value of the parent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParent() {
            return parent;
        }

        /**
         * Sets the value of the parent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParent(String value) {
            this.parent = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="job-launcher" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="job-parameters-extractor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Job {

        @XmlAttribute(name = "ref")
        @XmlSchemaType(name = "anySimpleType")
        protected String ref;
        @XmlAttribute(name = "job-launcher")
        @XmlSchemaType(name = "anySimpleType")
        protected String jobLauncher;
        @XmlAttribute(name = "job-parameters-extractor")
        @XmlSchemaType(name = "anySimpleType")
        protected String jobParametersExtractor;

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRef(String value) {
            this.ref = value;
        }

        /**
         * Gets the value of the jobLauncher property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobLauncher() {
            return jobLauncher;
        }

        /**
         * Sets the value of the jobLauncher property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobLauncher(String value) {
            this.jobLauncher = value;
        }

        /**
         * Gets the value of the jobParametersExtractor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobParametersExtractor() {
            return jobParametersExtractor;
        }

        /**
         * Sets the value of the jobParametersExtractor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobParametersExtractor(String value) {
            this.jobParametersExtractor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="on" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Next {

        @XmlAttribute(name = "on", required = true)
        protected String on;
        @XmlAttribute(name = "to", required = true)
        protected String to;

        /**
         * Gets the value of the on property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOn() {
            return on;
        }

        /**
         * Sets the value of the on property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOn(String value) {
            this.on = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="on" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="restart" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="exit-code" type="{http://www.w3.org/2001/XMLSchema}string" default="STOPPED" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Stop {

        @XmlAttribute(name = "on", required = true)
        protected String on;
        @XmlAttribute(name = "restart", required = true)
        protected String restart;
        @XmlAttribute(name = "exit-code")
        protected String exitCode;

        /**
         * Gets the value of the on property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOn() {
            return on;
        }

        /**
         * Sets the value of the on property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOn(String value) {
            this.on = value;
        }

        /**
         * Gets the value of the restart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRestart() {
            return restart;
        }

        /**
         * Sets the value of the restart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRestart(String value) {
            this.restart = value;
        }

        /**
         * Gets the value of the exitCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExitCode() {
            if (exitCode == null) {
                return "STOPPED";
            } else {
                return exitCode;
            }
        }

        /**
         * Sets the value of the exitCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExitCode(String value) {
            this.exitCode = value;
        }

    }

}
