//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.springframework.schema.beans.Bean;
import org.springframework.schema.beans.Ref;


/**
 * <p>Java class for taskletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="taskletType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="chunk" type="{http://www.springframework.org/schema/batch}chunkTaskletType" minOccurs="0"/>
 *         &lt;element name="transaction-attributes" type="{http://www.springframework.org/schema/batch}transaction-attributesType" minOccurs="0"/>
 *         &lt;element name="no-rollback-exception-classes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.springframework.org/schema/batch}includeElementGroup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="listeners" type="{http://www.springframework.org/schema/batch}stepListenersType" minOccurs="0"/>
 *         &lt;element ref="{http://www.springframework.org/schema/beans}bean" minOccurs="0"/>
 *         &lt;element ref="{http://www.springframework.org/schema/beans}ref" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}allowStartIfCompleteAttribute"/>
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transaction-manager" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="task-executor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="throttle-limit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taskletType", propOrder = {

})
public class TaskletType {

    protected ChunkTaskletType chunk;
    @XmlElement(name = "transaction-attributes")
    protected TransactionAttributesType transactionAttributes;
    @XmlElement(name = "no-rollback-exception-classes")
    protected TaskletType.NoRollbackExceptionClasses noRollbackExceptionClasses;
    protected StepListenersType listeners;
    @XmlElement(namespace = "http://www.springframework.org/schema/beans")
    protected Bean bean;
    @XmlElement(name = "ref", namespace = "http://www.springframework.org/schema/beans")
    protected Ref refAttribute;
    @XmlAttribute(name = "ref")
    protected String ref;
    @XmlAttribute(name = "method")
    protected String method;
    @XmlAttribute(name = "start-limit")
    protected String startLimit;
    @XmlAttribute(name = "transaction-manager")
    protected String transactionManager;
    @XmlAttribute(name = "task-executor")
    protected String taskExecutor;
    @XmlAttribute(name = "throttle-limit")
    protected String throttleLimit;
    @XmlAttribute(name = "allow-start-if-complete")
    protected String allowStartIfComplete;

    /**
     * Gets the value of the chunk property.
     * 
     * @return
     *     possible object is
     *     {@link ChunkTaskletType }
     *     
     */
    public ChunkTaskletType getChunk() {
        return chunk;
    }

    /**
     * Sets the value of the chunk property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChunkTaskletType }
     *     
     */
    public void setChunk(ChunkTaskletType value) {
        this.chunk = value;
    }

    /**
     * Gets the value of the transactionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionAttributesType }
     *     
     */
    public TransactionAttributesType getTransactionAttributes() {
        return transactionAttributes;
    }

    /**
     * Sets the value of the transactionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionAttributesType }
     *     
     */
    public void setTransactionAttributes(TransactionAttributesType value) {
        this.transactionAttributes = value;
    }

    /**
     * Gets the value of the noRollbackExceptionClasses property.
     * 
     * @return
     *     possible object is
     *     {@link TaskletType.NoRollbackExceptionClasses }
     *     
     */
    public TaskletType.NoRollbackExceptionClasses getNoRollbackExceptionClasses() {
        return noRollbackExceptionClasses;
    }

    /**
     * Sets the value of the noRollbackExceptionClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskletType.NoRollbackExceptionClasses }
     *     
     */
    public void setNoRollbackExceptionClasses(TaskletType.NoRollbackExceptionClasses value) {
        this.noRollbackExceptionClasses = value;
    }

    /**
     * Gets the value of the listeners property.
     * 
     * @return
     *     possible object is
     *     {@link StepListenersType }
     *     
     */
    public StepListenersType getListeners() {
        return listeners;
    }

    /**
     * Sets the value of the listeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepListenersType }
     *     
     */
    public void setListeners(StepListenersType value) {
        this.listeners = value;
    }

    /**
     * Gets the value of the bean property.
     * 
     * @return
     *     possible object is
     *     {@link Bean }
     *     
     */
    public Bean getBean() {
        return bean;
    }

    /**
     * Sets the value of the bean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bean }
     *     
     */
    public void setBean(Bean value) {
        this.bean = value;
    }

    /**
     * Gets the value of the refAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Ref }
     *     
     */
    public Ref getRefAttribute() {
        return refAttribute;
    }

    /**
     * Sets the value of the refAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ref }
     *     
     */
    public void setRefAttribute(Ref value) {
        this.refAttribute = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the startLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartLimit() {
        return startLimit;
    }

    /**
     * Sets the value of the startLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartLimit(String value) {
        this.startLimit = value;
    }

    /**
     * Gets the value of the transactionManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionManager() {
        return transactionManager;
    }

    /**
     * Sets the value of the transactionManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionManager(String value) {
        this.transactionManager = value;
    }

    /**
     * Gets the value of the taskExecutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskExecutor() {
        return taskExecutor;
    }

    /**
     * Sets the value of the taskExecutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskExecutor(String value) {
        this.taskExecutor = value;
    }

    /**
     * Gets the value of the throttleLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThrottleLimit() {
        return throttleLimit;
    }

    /**
     * Sets the value of the throttleLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThrottleLimit(String value) {
        this.throttleLimit = value;
    }

    /**
     * Gets the value of the allowStartIfComplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowStartIfComplete() {
        return allowStartIfComplete;
    }

    /**
     * Sets the value of the allowStartIfComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowStartIfComplete(String value) {
        this.allowStartIfComplete = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.springframework.org/schema/batch}includeElementGroup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;attGroup ref="{http://www.springframework.org/schema/batch}mergeAttribute"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "includeElementGroup"
    })
    public static class NoRollbackExceptionClasses {

        @XmlElement(name = "include")
        protected List<ChunkTaskletType.RetryableExceptionClasses.Include> includeElementGroup;
        @XmlAttribute(name = "merge")
        protected Boolean merge;

        /**
         * Gets the value of the includeElementGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the includeElementGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncludeElementGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ChunkTaskletType.RetryableExceptionClasses.Include }
         * 
         * 
         */
        public List<ChunkTaskletType.RetryableExceptionClasses.Include> getIncludeElementGroup() {
            if (includeElementGroup == null) {
                includeElementGroup = new ArrayList<ChunkTaskletType.RetryableExceptionClasses.Include>();
            }
            return this.includeElementGroup;
        }

        /**
         * Gets the value of the merge property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMerge() {
            return merge;
        }

        /**
         * Sets the value of the merge property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMerge(Boolean value) {
            this.merge = value;
        }

    }

}
