//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:54:47 PM CEST 
//


package org.springframework.schema.batch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transaction-attributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transaction-attributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="propagation">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="REQUIRED"/>
 *             &lt;enumeration value="SUPPORTS"/>
 *             &lt;enumeration value="MANDATORY"/>
 *             &lt;enumeration value="REQUIRES_NEW"/>
 *             &lt;enumeration value="NOT_SUPPORTED"/>
 *             &lt;enumeration value="NEVER"/>
 *             &lt;enumeration value="NESTED"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isolation" type="{http://www.springframework.org/schema/batch}isolationType" />
 *       &lt;attribute name="timeout" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transaction-attributesType")
public class TransactionAttributesType {

    @XmlAttribute(name = "propagation")
    protected String propagation;
    @XmlAttribute(name = "isolation")
    protected IsolationType isolation;
    @XmlAttribute(name = "timeout")
    protected String timeout;

    /**
     * Gets the value of the propagation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropagation() {
        return propagation;
    }

    /**
     * Sets the value of the propagation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropagation(String value) {
        this.propagation = value;
    }

    /**
     * Gets the value of the isolation property.
     * 
     * @return
     *     possible object is
     *     {@link IsolationType }
     *     
     */
    public IsolationType getIsolation() {
        return isolation;
    }

    /**
     * Sets the value of the isolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsolationType }
     *     
     */
    public void setIsolation(IsolationType value) {
        this.isolation = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

}
