Document: geoknow-generator-ui
Title: Debian geoknow-generator-ui Manual
Author: <insert document author here>
Abstract: This manual describes what geoknow-generator-ui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/geoknow-generator-ui/geoknow-generator-ui.sgml.gz

Format: postscript
Files: /usr/share/doc/geoknow-generator-ui/geoknow-generator-ui.ps.gz

Format: text
Files: /usr/share/doc/geoknow-generator-ui/geoknow-generator-ui.text.gz

Format: HTML
Index: /usr/share/doc/geoknow-generator-ui/html/index.html
Files: /usr/share/doc/geoknow-generator-ui/html/*.html
