/* CVS $Id: $ */
package com.ontos.ldiw.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import java.io.ByteArrayInputStream;
 
/**
 * Vocabulary definitions from ldis-0.1.12.ttl 
 * @author Auto-generated by schemagen on 10 Jun 2015 15:00 
 */
public class LDIS {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    private static final String SOURCE = 
           "@prefix :      <http://stack.linkeddata.org/ldis-schema/> .        \n"
         + "@prefix schema: <http://schema.org/> .        \n"
         + "@prefix d2rq:  <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> .        \n"
         + "@prefix void:  <http://rdfs.org/ns/void#> .        \n"
         + "@prefix owl:   <http://www.w3.org/2002/07/owl#> .        \n"
         + "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .        \n"
         + "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .        \n"
         + "@prefix sd:    <http://www.w3.org/ns/sparql-service-description#> .        \n"
         + "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .        \n"
         + "@prefix dcmit: <http://purl.org/dc/dcmitype/> .        \n"
         + "@prefix dcterms: <http://purl.org/dc/terms/> .        \n"
         + "@prefix prov:  <http://www.w3.org/ns/prov#> .        \n"
         + "@prefix foaf:  <http://xmlns.com/foaf/> .        \n"
         + ":ExtractionService  a    owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for extraction.\"@en ;        \n"
         + "        rdfs:label       \"Extraction Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + "foaf:homepage  a     rdf:Property ;        \n"
         + "        rdfs:domain  :StackComponent ;        \n"
         + "        rdfs:label   \"homepage\"@en .        \n"
         + ":user   a            rdf:Property ;        \n"
         + "        rdfs:domain  :EmailService ;        \n"
         + "        rdfs:label   \"user\"@en .        \n"
         + ":ExplorationService  a   owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for exploration.\"@en ;        \n"
         + "        rdfs:label       \"Exploration Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":serviceUrl  a       rdf:Property ;        \n"
         + "        rdfs:domain  :ComponentService ;        \n"
         + "        rdfs:label   \"Service URL\"@en ;        \n"
         + "        rdfs:range   xsd:string .        \n"
         + ":InterlinkingService  a  owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for interlinking.\"@en ;        \n"
         + "        rdfs:label       \"Interlinking Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":EmailService  a         owl:Class ;        \n"
         + "        rdfs:label       \"requires \"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":ComponentService  a     owl:Class ;        \n"
         + "        rdfs:label       \"Component Service\"@en ;        \n"
         + "        rdfs:subClassOf  owl:Thing .        \n"
         + ":       a                    owl:Ontology ;        \n"
         + "        dcterms:contributor  \"Alejandra Garcia Rojas\"^^xsd:string ;        \n"
         + "        dcterms:descripton   \"Schema for integrating Software components from the Linked Data Stack\"@en ;        \n"
         + "        owl:versionInfo      \"0.1.2\"^^xsd:string .        \n"
         + ":providesService  a   owl:ObjectProperty ;        \n"
         + "        rdfs:comment  \"A component in the stack provides a service of a given type\"@en ;        \n"
         + "        rdfs:domain   :StackComponent ;        \n"
         + "        rdfs:label    \"Provides Service\"@en ;        \n"
         + "        rdfs:range    :ComponentService .        \n"
         + ":StackComponent  a       owl:Class ;        \n"
         + "        rdfs:label       \"Stack Component\"@en ;        \n"
         + "        rdfs:subClassOf  owl:Thing .        \n"
         + ":requires  a          owl:ObjectProperty ;        \n"
         + "        rdfs:comment  \"A component depends on another component to work\"@en ;        \n"
         + "        rdfs:label    \"requires\"@en .        \n"
         + ":PublicationService  a   owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for quality analysis.\"@en ;        \n"
         + "        rdfs:label       \"Publication Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":WorkflowService  a      owl:Class ;        \n"
         + "        rdfs:label       \"requires \"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":AnalysisService  a      owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for analysis.\"@en ;        \n"
         + "        rdfs:label       \"Analysis Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":EnrichmentService  a    owl:Class ;        \n"
         + "        rdfs:label       \"Enrichment Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + "sd:Service  a       rdfs:Class ;        \n"
         + "        rdfs:label  \"Service URL\"@en .        \n"
         + ":TransformationService        \n"
         + "        a                owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for transformation.\"@en ;        \n"
         + "        rdfs:label       \"Transformation Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":AuthoringService  a     owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for authoring.\"@en ;        \n"
         + "        rdfs:label       \"Component Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + "sd:NamedGraph  a    rdfs:Class ;        \n"
         + "        rdfs:label  \"Service URL\"@en .        \n"
         + ":QualityAnalysisService        \n"
         + "        a                owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for quality analysis.\"@en ;        \n"
         + "        rdfs:label       \"Quality Analysis Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":password  a         rdf:Property ;        \n"
         + "        rdfs:domain  :EmailService ;        \n"
         + "        rdfs:label   \"password\"@en .        \n"
         + "dcterms:hasVersion  a  rdf:Property ;        \n"
         + "        rdfs:domain  :StackComponent ;        \n"
         + "        rdfs:label   \"has version\"@en .        \n"
         + ":connectionString  a  rdf:Property ;        \n"
         + "        rdfs:label  \"connection string\"@en .        \n"
         + ":StorageService  a       owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for storage.\"@en ;        \n"
         + "        rdfs:label       \"Storage Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":SPARQLEndPointService        \n"
         + "        a                owl:Class ;        \n"
         + "        rdfs:comment     \"Represents a Sparql query end point\"@en ;        \n"
         + "        rdfs:label       \"SPARQL endpoint Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService , :QueryEndPointService .        \n"
         + ":QueryEndPointService        \n"
         + "        a                owl:Class ;        \n"
         + "        rdfs:comment     \"Represents a query end point\"@en ;        \n"
         + "        rdfs:label       \"Query endpoint Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService , :ExplorationService .        \n"
         + "foaf:mbox  a         rdf:Property ;        \n"
         + "        rdfs:domain  :EmailService ;        \n"
         + "        rdfs:label   \"e-mail\"@en .        \n"
         + ":VisualizationService        \n"
         + "        a                owl:Class ;        \n"
         + "        rdfs:label       \"Visualization Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":apiKey  a          rdf:Property ;        \n"
         + "        rdfs:label  \"Enrichment Service\"@en .        \n"
         + ":CleaningService  a      owl:Class ;        \n"
         + "        rdfs:comment     \"Represents the agent responsible for storage.\"@en ;        \n"
         + "        rdfs:label       \"Cleaning Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService .        \n"
         + ":integrates  a        owl:ObjectProperty ;        \n"
         + "        rdfs:comment  \"A component integrates another component\"@en ;        \n"
         + "        rdfs:label    \"integrates\"@en .        \n"
         + ":SecuredSPARQLEndPointService        \n"
         + "        a                owl:Class ;        \n"
         + "        rdfs:label       \"Secured SPARQL Endpoint Service\"@en ;        \n"
         + "        rdfs:subClassOf  :ComponentService , :SPARQLEndPointService .        \n"
    ;

    /** Read the ontology definition into the source model */ 
    static { 
        m_model.read( new ByteArrayInputStream( SOURCE.getBytes() ), null, "N3" );
    }

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://stack.linkeddata.org/ldis-schema/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.1.2";
    

    public static Model getModel() {return m_model;}

    public static final Property apiKey = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/apiKey" );
    
    public static final Property connectionString = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/connectionString" );
    
    /** <p>A component integrates another component</p> */
    public static final Property integrates = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/integrates" );
    
    public static final Property password = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/password" );
    
    /** <p>A component in the stack provides a service of a given type</p> */
    public static final Property providesService = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/providesService" );
    
    /** <p>A component depends on another component to work</p> */
    public static final Property requires = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/requires" );
    
    public static final Property serviceUrl = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/serviceUrl" );
    
    public static final Property user = m_model.createProperty( "http://stack.linkeddata.org/ldis-schema/user" );
    
    /** <p>Represents the agent responsible for analysis.</p> */
    public static final Resource AnalysisService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/AnalysisService" );
    
    /** <p>Represents the agent responsible for authoring.</p> */
    public static final Resource AuthoringService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/AuthoringService" );
    
    /** <p>Represents the agent responsible for storage.</p> */
    public static final Resource CleaningService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/CleaningService" );
    
    public static final Resource ComponentService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/ComponentService" );
    
    public static final Resource EmailService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/EmailService" );
    
    public static final Resource EnrichmentService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/EnrichmentService" );
    
    /** <p>Represents the agent responsible for exploration.</p> */
    public static final Resource ExplorationService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/ExplorationService" );
    
    /** <p>Represents the agent responsible for extraction.</p> */
    public static final Resource ExtractionService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/ExtractionService" );
    
    /** <p>Represents the agent responsible for interlinking.</p> */
    public static final Resource InterlinkingService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/InterlinkingService" );
    
    /** <p>Represents the agent responsible for quality analysis.</p> */
    public static final Resource PublicationService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/PublicationService" );
    
    /** <p>Represents the agent responsible for quality analysis.</p> */
    public static final Resource QualityAnalysisService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/QualityAnalysisService" );
    
    /** <p>Represents a query end point</p> */
    public static final Resource QueryEndPointService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/QueryEndPointService" );
    
    /** <p>Represents a Sparql query end point</p> */
    public static final Resource SPARQLEndPointService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/SPARQLEndPointService" );
    
    public static final Resource SecuredSPARQLEndPointService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/SecuredSPARQLEndPointService" );
    
    public static final Resource StackComponent = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/StackComponent" );
    
    /** <p>Represents the agent responsible for storage.</p> */
    public static final Resource StorageService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/StorageService" );
    
    /** <p>Represents the agent responsible for transformation.</p> */
    public static final Resource TransformationService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/TransformationService" );
    
    public static final Resource VisualizationService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/VisualizationService" );
    
    public static final Resource WorkflowService = m_model.createResource( "http://stack.linkeddata.org/ldis-schema/WorkflowService" );
    
}
